### ISSUE TITLE
Cannot compile BASC in a Mac terminal

### ISSUE THREAD

**Issue by zoeye859** [petehague/BASC#3]
Hi Peter, after cloning the repo, I tried 'make' in my Mac terminal, I received an error looks like this:

Zoes-MacBook-Pro:BASC zoeye51$ make
CXXFLAGS='-std=c++11' python setup.py build
running build
running build_ext
building 'skimage' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.6
creating build/temp.macosx-10.7-x86_64-3.6/source
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda/include -arch x86_64 -I/anaconda/include -arch x86_64 -I/anaconda/include/python3.6m -c source/pyskimage.cpp -o build/temp.macosx-10.7-x86_64-3.6/source/pyskimage.o -std=c++11
In file included from source/pyskimage.cpp:3:
source/../include/skimage.hpp:4:10: fatal error: 'cinttypes' file not found
#include <cinttypes>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

Another researcher, also a Mac user, faces the same problem. Any idea?

P.S. I have Anaconda installed.

**Comment by petehague** [comment]
This seems to be primarily an issue with clang (the default Mac C compiler) which you get when you type gcc. If you use homebrew to install proper gcc, and then set CC=gcc-8 then the issue may be resolved.

**Comment by petehague** [comment]
This is due to the C compiler that comes with Anaconda. The current version of BaSC can now be built using the native Mac C compiler (clang) if you remove all references to Anaconda in your PATH - and then can be imported once you re-enable Anaconda.

I will leave this issue open for now as I will be trying to allow BaSC to compile with Anaconda.

**Comment by petehague** [comment]
There is a new version of the setup script for Mac; could you please test it.

**Comment by zoeye859** [comment]
Sure! Just tested it! It works!

**Comment by petehague** [comment]
Setup script has been tested on a mac with Anaconda and works. Closing the issue
