### ISSUE TITLE
cannot run 'example.py'

### ISSUE THREAD

**Issue by zoeye859** [petehague/BASC#4]
Hi Peter, I tried BASC on a linux machine. Though installed fine, but running 'python example.py' gives me error messages:
make
CXXFLAGS='-std=c++11' python setup.py build
running build
running build_ext
building 'skimage' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/source
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/gcc/gcc-7.3.0/include -fPIC -I/usr/local/python3.5/include/python3.5m -c source/pyskimage.cpp -o build/temp.linux-x86_64-3.5/source/pyskimage.o -std=c++11
/import/appcs-local/gcc/gcc-7.3.0/bin/../libexec/gcc/x86_64-pc-linux-gnu/7.3.0/cc1plus: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory
error: command 'gcc' failed with exit status 1
make: *** [pyskimage] Error 1

I was using python3.5 and gcc 7.3.0.

**Comment by petehague** [comment]
Have you checked that the version of Python that you installed the extension with is the same one that ran example.py?

**Comment by zoeye859** [comment]
Yes, I used Python 3.5. I installed the newest BaSC, then ran python example.py. It gave me a different error:
python example.py 
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    import basc
  File "/import/appcg1/hy297/BASC/basc.py", line 6, in <module>
    import bascmod
ImportError: dynamic module does not define module export function (PyInit_bascmod)

Any advice?

**Comment by zoeye859** [comment]
Thank you for fixing the problem! Now everything works!

**Comment by petehague** [comment]
Solved this now so closing
